to_xccdf: Enable STIGViewer support for automatic CCI descriptions.
mitre/inspec_tools pull request #222
Opened 2021-04-09 23:08 UTC by janeuner

XCCDF ident elements with CCI values should use a cyber.mil/cci system attribute to display correctly in STIG Viewer.

> Before:
> ![20210409_rule_with_public_cci](https://user-images.githubusercontent.com/7094088/114248838-68410800-995e-11eb-8078-7490335fd5af.png)

> After:
> ![20210409_rule_with_mil_cci](https://user-images.githubusercontent.com/7094088/114248848-70994300-995e-11eb-92aa-5bc1ad8b5aa0.png)

2021-04-12 17:39 UTC, janeuner commented
I was also able to figure out the Legacy IDs field.  Adding to the PR since they are closely related in the data schema.
![20210412_rule_with_legacy_ids](https://user-images.githubusercontent.com/7094088/114437404-22698700-9b8c-11eb-8635-60c121c2f591.png)

2021-04-15 20:57 UTC, Bialogs requested changes
Instead of making the `rule_idents` method aware of the type of system being created, move back the logic to the initializer for the `Ident` itself. This way the logic for determine legacy or CCI can be reused if we need to include this information on other output formats.

Not sure what you would have to parse within the `control['cci']` or `control['legacy']` to make that determination.

Essentially what would be acceptable is 
```ruby
# to_xxdf.rb#build_rule_idents
# ...
idents.map { Ident.new(identifier) }

# HappyMapperTools::Benchmark::Ident
class Ident
  def initialize(ident_string)
    # Some parsing to determine CCI or Legacy
   @system = system
    @ident = ident
  end
end
```

2021-04-15 20:58 UTC, Bialogs commented
Thanks for the changes. Makes sense since these legacy IDs are now being parsed from the XCCDF content. Please take a look at my review.

2021-04-16 15:05 UTC, Bialogs approved these changes

2021-04-16 16:33 UTC, merged